coinbase/geoengineer

- lib/geoengineer/resources/aws_vpc.rb
- spec/resources/aws_vpc_spec.rb
- New feature
This adds the Aws VPC resource to GeoEngineer, so that we can begin to
codify our existing VPC's.
Added a couple specs.
@mentions:
==========
@grahamjenson
> New: Codify AwsVpc

- .irbrc
- lib/geoengineer/resources/aws_route_table_association.rb
- spec/resources/aws_route_table_association_spec.rb
- New feature
Adding the ability to codify route_table_associations to Geo.
One thing to note here is that since route table associations don't have
the ability to add tags, the Geo ID is the concatenation of the 2
required attributes for a route table association: the subnet ID and the
route table ID. I concatenated them with a `|` so that it was a bit more
human readable (as both the subnet ID and route table ID use `-` in
their ID's).
Also added a barebones `.irbrc` file that simply requires
`./lib/geoengineer`. This allows you to:
```
bundle exec irb
```
And immediately start using the methods and classes defined in Geo.
Added some tests.
@mentions: …
> New: Add route_table_associations to Geo

- lib/geoengineer/resources/aws_dhcp_options_set.rb
- lib/geoengineer/utils/has_validations.rb
- spec/resources/aws_vpc_dhcp_options_set.rb
- spec/utils/has_validations_spec.rb
- New feature
Added the ability to codify DHCP Options set.
By itself, a pretty standard resource.
Also added a couple additional validations:
- validate_at_least_one_present, which checks that at least on of the
specified attributes has been defined. This is useful when there are
number of attributes that could be defined, and we need at least one.
- validate_only_one_present, which is similar to at_least_one_present,
but checks that exactly one of the attributes is defined.
Added specs
@mentions:
==========
@grahamjenson
> New: Add Aws Vpc DHCP Options Set

- lib/geoengineer/resources/aws_nat_gateway.rb
- spec/resources/aws_nat_gateway_spec.rb
- New feature
Add the ability to codify AWS Nat Gateways.
The only weird thing with this resource is that AWS SDK has buried the
information about the IP allocation in a `nat_gateway_addresses` array,
even though a Gateway can have exactly 1 EIP allocation. ¯\_(ツ)_/¯
The usual specs.
@mentions:
==========
@grahamjenson
@lukedemi
> New: Add AWS Nat Gateway

- lib/geoengineer/resources/aws_vpn_gateway.rb
- spec/resources/aws_vpn_gateway_spec.rb
- New feature
Added the ability to codify AWS VPN Gateways, also known as Private
Gateways.
The only thing that really needs scrutiny here is whether or not to
require the `vpc_id`.
The Terraform docs have it as optional, but seems kinda silly to create
one without attaching to a VPC. I could be wrong though, and thus
unfairly limiting Geo.
The usual.
> New: Add AWS VPN (Private) Gateway

- lib/geoengineer/resources/aws_customer_gateway.rb
- lib/geoengineer/resources/aws_instance.rb
- lib/geoengineer/resources/aws_route_table.rb
- lib/geoengineer/resources/aws_security_group.rb
- lib/geoengineer/resources/aws_subnet.rb
- lib/geoengineer/resources/aws_vpc.rb
- lib/geoengineer/resources/aws_vpc_dhcp_options.rb
- spec/resources/aws_customer_gateway_spec.rb
- New feature
Add the ability to codify AWS Customer Gateways.
Also realized that in the case where the existing AWS resources don't
have a `Name` tag, the code I had been using would fail, due to:
```
irb(main):001:0> nil[:foo]
NoMethodError: undefined method `[]' for nil:NilClass
```
So I changed all instances where I could find of tag lookup to:
```
.merge(
{
_terraform_id: ...,
_geo_id: resource[:tags].find { |tag| tag[:key] == "Name" }&.dig(:value)
}
)
```
Which will return a `nil` geo ID if the `Name` tag does not exist.
```
irb(main):001:0> nil&.dig(:foo)
=> nil
```
The usual tests
@mentions:
==========
@grahamjenson
> New: Add aws_customer_gateway

- lib/geoengineer/resources/aws_vpn_gateway_attachment.rb
- spec/resources/aws_vpn_gateway_attachment_spec.rb
- New feature
Add the ability to codify AWS VPN Gateway Attachments, which in my view,
are an inferior resource. Seems like you should almost always define the
VPC association in the VPN Gateway declaration. But hey, that's just me.
This one also uses the Crc32 Hashcode, which I realized means that I can
actually derive the terraform ID without fetching remote resources.
Cool.
The usual.
> New: Add AWS VPN Gateway Attachment

- lib/geoengineer/cli/geo_cli.rb
- lib/geoengineer/environment.rb
- lib/geoengineer/resources/aws_iam_policy.rb
- lib/geoengineer/resources/aws_iam_policy_attachment.rb
- lib/geoengineer/utils/has_resources.rb
- spec/resources/aws_iam_policy_attachment_spec.rb
Previously geo would validate the names of all resources to avoid collisions. Here, the validation changes so that geo only validates the singularity of names across one resource type
> Fixes resource validation on naming for use with aws_iam_policy_attachment

- lib/geoengineer/resources/aws_customer_gateway.rb
- lib/geoengineer/resources/aws_instance.rb
- lib/geoengineer/resources/aws_internet_gateway.rb
- lib/geoengineer/resources/aws_network_acl.rb
- lib/geoengineer/resources/aws_route_table.rb
- lib/geoengineer/resources/aws_security_group.rb
- lib/geoengineer/resources/aws_subnet.rb
- lib/geoengineer/resources/aws_vpc.rb
- lib/geoengineer/resources/aws_vpc_dhcp_options.rb
- lib/geoengineer/resources/aws_vpn_gateway.rb
- spec/resources/aws_network_acl_rule_spec.rb
- spec/resources/aws_network_acl_spec.rb
- spec/resources/aws_security_group_spec.rb
- Bug fix
Original syntax:
```
_geo_id: resource[:tags] ? resource[:tags].select { |x| x[:key] == "Name" }.first[:value] : nil
```
While this would work for cases where resource had or did not have tags,
it would fail for the case where it had tags, but not a "Name" tag.
I modified it to this:
```
_geo_id: resource[:tags].find { |tag| tag[:key] == "Name" }&.dig(:value)
```
Which traded one problem for another - if the resource didn't have ANY
tags defined, it would error.
So I solved with this:
```
_geo_id: resource[:tags]&.find { |tag| tag[:key] == "Name" }&.dig(:value)
```
Which now covers all the bases.
Added an additional spec.
@mentions:
========== …
> Fix: Account for resources with no tags

- lib/geoengineer/resources/aws_nat_gateway.rb
- lib/geoengineer/resources/aws_network_acl_rule.rb
- lib/geoengineer/resources/aws_route.rb
- lib/geoengineer/resources/aws_route53_record.rb
- lib/geoengineer/resources/aws_route_table_association.rb
- lib/geoengineer/resources/aws_vpc_dhcp_options_association.rb
- lib/geoengineer/resources/aws_vpc_endpoint.rb
- lib/geoengineer/resources/aws_vpn_connection_route.rb
- lib/geoengineer/resources/aws_vpn_gateway_attachment.rb
If resource doesn't support flags, set `support_flags?` to `false`
> Explicitly mark those resources that don't support tagging

- lib/geoengineer/resource.rb
- lib/geoengineer/resources/aws_lambda_alias.rb
- lib/geoengineer/resources/aws_lambda_permission.rb
- spec/resources/aws_lambda_alias_spec.rb
- spec/resources/aws_lambda_permission_spec.rb
- New feature
This introduces the concept of a Permission for AWS Lambda's.
My guess is that this resource will require a refactor soonish, due to:
- It being a relatively nascent AWS product
- Becuase of this ^, updates to AWS SDK are quite possible
- Listing remote policies is currently only configured for the lastest
version of a function
- Terraform arguments/state do not map nicely to data returned from the
AWS SDK
- No support for pagination yet, and unlike other resources, there is
high potential for a large number of lambda functions
I also fix a rubocop error in `lib/geoengineer/resource.rb`, and a
couple bugs with the AWS Lambda Alias resource and associated specs. …
> New: Add Lambda Permission to Geo

- lib/geoengineer/resources/aws_lambda_event_source_mapping.rb
- spec/resources/aws_lambda_event_source_mapping_spec.rb
- New feature
Add the ability to codify AWS Lambda Event Source Mappings to
GeoEngineer. This resource was a bit tricky, as AWS doesn't return many
of the attributes required to create a mapping. The main problem being
that a `function_name` is required, but a `function_arn` is returned.
I'm assuming that all ARN's follow the convention I've noticed so far
of:
```
arn:aws:lambda:<region>:<account_id>:function:<function_name>:alias|version
```
To allow Geo to match remote with local resources, I built a helper method to
extract the function_name from the function_arn.
The usual specs, plus one for `#_extract_name_from_arn`.
> New: Add AWS Lambda Event Source Mapping to Geo

- lib/geoengineer/utils/crc32.rb
- spec/utils/crc32_spec.rb
Ran into a case where a remote route didn't have a destination cidr block I think, so the hashcode failed.
> Account for nil string values being passed to hashcode

- .gitignore
- lib/geoengineer/resources/aws_security_group.rb
- lib/geoengineer/utils/has_validations.rb
- Refactor
I expected the method `GeoEngineer::Resource#validate_cidr_block` to
behave like the other validation methods that returned an array of
errors. However the method returned an array no matter if the cidr block
was invalid or not, and the method consumer was supposed to work out if
the returned data actually signified an error or not.
I didn't like how this worked, so I rewrote it to only return an error
message if the cidr block is actually invalid.
Also added Vim swap files to the `.gitignore`
All existing tests pass.
@mentions:
==========
@grahamjenson
> Refactor: validate_cidr_block

- lib/geoengineer/resource.rb
- New feature
While I was creating a new template, I realized that for a number of
cases, I need the terraform ID of a resource if it is known, but it
doesn't exist yet, then I need to the terraform reference to that ID.
So I created a method that does that.
> New: Add new method

- lib/geoengineer/utils/has_attributes.rb
- spec/utils/has_attributes_spec.rb
- New feature
So, I was working on a template, and I codified a default path forward
that works for most of our environments. A few however, are different,
and so I tried to override those values using a block. The resource in
question uses tags for its `_geo_id`, so I updated the `Name` tag.
After I did this, I assumed that the `_geo_id` would update, but once
it's been called, the value is static, and the lambda used to calculate
it was gone. That meant that the only way to accomodate this was to move
the value into a template parameter, which seemed like a suboptimal
solution.
Instead, I modified the logic so that we cache the Proc used to
calculate the value, and then added a reset function that …
> New: Add reset capability 

- lib/geoengineer/resource.rb
- lib/geoengineer/utils/has_attributes.rb
- spec/resource_spec.rb
- spec/utils/has_attributes_spec.rb
- Refactor
Realized that when I tried to use the `#reset` functionality in a real
world project, it didn't reset the remote resource, which meant that
_terraform_id was not refreshed, which meant that the plan still wasn't
up to date.
So I renamed the `reset` and `eager_load` to `reset_attributes` and
`eager_load_attributes`, and added a `reset` function to
`GeoEngineer::Resource`, which calls `reset_attributes` and also resets
the remote variables such that the resource re-calculates the correct
things.
Added some tests
@mentions:
==========
@grahamjenson
> Refactor: #reset

- lib/geoengineer/resources/aws_main_route_table_association.rb
- lib/geoengineer/resources/aws_route_table_association.rb
- lib/geoengineer/resources/aws_vpc_dhcp_options_association.rb
- Refactor
Since most of the association resources are listed/described via their
parent resource (i.e. VPC, route table, subnet, etc...), under the hood,
Terraform expects certain attributes to be present in the state file so
that it can verify that the remote resource actually exists.
So I updated the `#terraform_state` methods on the resources to add
those attributes to the state output.
By including this code in another repo and running `./geo plan`
@mentions:
==========
@grahamjenson
> Refactor: Update association resources

- lib/geoengineer/resources/aws_route.rb
- Bug fix
In my original implementation, I was trying to extract the
route_table_id from the route object, forgetting that since routes are
nested, the route_table_id would be at a different level of the
response.
I've fixed that now.
Manually checking output in `irb`
@mentions:
==========
@grahamjenson
> Fix: update aws_route fetching, caching

- lib/geoengineer/resources/aws_network_acl_rule.rb
- lib/geoengineer/resources/aws_route.rb
- Clean up
Routes that point to `local` are automatically created when a route
table is created, and cannot be changed.
Routes that point to a VPC endpoint are automatically created when a VPC
endpoint is associated with a route table, and cannot be modified.
NACL Rules that have the number 32767 are automatically created when a
NACL is created, and cannot be modified.
Therefore, they should not be returned by the `#_fetch_remote_resources`
method.
@mentions:
==========
@grahamjenson
> Other: Exclude auto-generated resources

- lib/geoengineer/resources/aws_db_instance.rb
- Refactor
From Terraform:
> `username` - (Required unless a `snapshot_identifier` or
> `replicate_source_db` is provided) Username for the master DB user.
@mentions:
==========
@rob
> Refactor: Limit validations

- lib/geoengineer/resources/aws_iam_role_policy.rb
- spec/resources/aws_iam_role_spec.rb
- spec/resources/aws_iam_rule_policy_spec.rb
- New feature
Adding aws_iam_role_policy to Geo.
This one is a bit complex, as you first need to list all roles, then for
each role, list role policies, and then get the actual policy.
Added a spec
@mentions:
==========
@lukedemi @jackkearney
> New: Add aws_iam_role_policy

- lib/geoengineer/resources/aws_redshift_cluster.rb
- New feature
Copied the username/password logic from `aws_db_instance` to
`aws_redshift_cluster`. This allows us to skip codifying the username
and password for a cluster if remote resource already exists.
What this means is that in practice, cluster(s) will generally be
created manually either via the AWS CLI, or the AWS Web console, and
then codified. This allows the user to sidestep the issue of having to
store sensitive data in the codifying repo.
@mentions:
==========
@lukedemi
> New: Update aws_redshift_cluster

- lib/geoengineer/resources/aws_iam_policy.rb
- lib/geoengineer/resources/aws_iam_role_policy.rb
- lib/geoengineer/utils/has_validations.rb
- spec/utils/has_validations_spec.rb
- New feature
We've run into some errors where our policies are too large, but we
don't catch those errors until we actually try to apply the policies,
forcing us to quickly put together PR's to fix the policies.
This validation should enable us to catch those errors during the
planning stage.
Added some specs
@mentions:
==========
@grahamjenson
@lukedemi
> New: Add Policy Length Validation

- lib/geoengineer/resources/aws_load_balancer_backend_server_policy.rb
- lib/geoengineer/resources/aws_load_balancer_policy.rb
- spec/resources/aws_load_balancer_policy_spec.rb
- Refactor
The previous iteration of these resources:
- aws_load_balancer_policy
- aws_load_balancer_backend_server_policy
were not functional, as the `_terraform_id` didn't match that used by
Terraform, and I'm not sure the `_fetch_remote_resources` calls worked
properly. That has been fixed, and we should be able to codify these
resources now.
The one thing I will call out is that since you need to make a
relatively large number of calls for the aws_load_balancer_policy
resource.
Locally, works like a charm.
@mentions:
==========
@lukedemi
> Refactor: Upate load balancer related policies

- lib/geoengineer/resources/aws_lambda_alias.rb
- spec/resources/aws_lambda_alias_spec.rb
- Bug fix
Last PR I was lazy. While that was also a bug, it wasn't the only bug.
Turns out the function_name attribute expecs the function_arn. I fixed
that, and added a test to ensure that it actually works as expected now.
Added a test.
@mentions:
==========
@grahamjenson
> Fix: aws_lambda_alias

- Gemfile.lock
- lib/geoengineer/resource.rb
- spec/resource_spec.rb
- spec/resources/aws_kinesis_stream_spec.rb
- New feature
We've run into some issues with sensitive/difficult resources that we
don't intend to codify, and would like to remove them from planning and
status commands.
This PR adds a simple way to specify which resources should be excluded.
Alternatives considered:
- monkey patching in downstream projects (seemed hacky)
- lambda based exclusions (more flexible, but also a bit more complex)
Added a test case
@mentions:
==========
@grahamjenson @lukedemi
> New: Allow resources to be ignored

- lib/geoengineer/resource.rb
- lib/geoengineer/resources/aws_lambda_permission.rb
- spec/resource_spec.rb
- spec/resources/aws_lambda_permission_spec.rb
- New feature
This PR contains 2 changes:
- An update to AWS Lambda Permission, allowing it to
`_fetch_remote_as_individual`
- An update to `_resources_to_ignore` logic, which makes it more
impervious to possible end user mistakes
Added some specs, moved a couple others
@mentions:
==========
@lukedemi
> New: Update AWS Lambda Permission, harden method

- lib/geoengineer/environment.rb
- lib/geoengineer/resource.rb
- spec/resource_spec.rb
- Refactor
In some of the repositories where we are using Geo, we only have
environments, and no projects. However, we still want to apply a set of
org/ProjectName tags to all of the resources. Another use case would be
auto-tagging the environment name on every resource.
We replace `merge_project_tags` with `merge_parent_tags` which then
loops through both `@environment` and `@project`.
Also had to refactor `GeoEngineer::Resource` a bit to get the total class LOC under 200 again.
Modified existing test cases to cover this new behavior.
@mentions:
==========
@grahamjenson @lukedemi
> New: All environments to have tags

- lib/geoengineer/cli/geo_cli.rb
- Refactor
Right now, every time there are no geo patches, we got an extra log
line. Seeing as the default should be no patches, I think it makes sense
to _only_ log when something non-standard is loaded.
Doing this via a begin/rescue isn't ideal, as we'd be rescueing into the
default state, where we want to no-op. Instead, we check if the file
exists, and then require the file if so.
@mentions:
==========
@lukedemi
> Refactor: Only log if patches loaded

- lib/geoengineer/resources/aws_kms_key.rb
- lib/geoengineer/utils/aws_clients.rb
- spec/resources/aws_kms_key_spec.rb
- spec/spec_helper.rb
uses aws `description` field for `_geo_id` since this resource doesn't support tags
> add aws_kms_key

- Gemfile.lock
- geoengineer.gemspec
- lib/geoengineer/environment.rb
A quick performance test revealed that we could parallelize this portion
of the plan process to reduce overall time by a few seconds.
Given a laptop with 8 logical cores, I observed the following timing
differences for the modified section of code:
Optimization          | Execution time
----------------------|------------------
None (current code)   | 8.97s
4 threads             | 2.58s
6 threads             | 1.67s
8 threads             | 1.32s
16 threads            | 1.44s
Experiment revealed that setting the number of threads to the number of
logical cores gave the optimal reduction in execution time.
> Parallelize state file generation

- lib/geoengineer/cli/terraform_commands.rb
Terraform exposes a `-parallelism` flag for the `plan` and `apply`
commands, allowing you to specify the degree of parallelism in the run.
We can take advantage of this to speed up these commands. Running on a
laptop with 8 cores, I observed the following improvements when
specifying the following flag for `terraform plan`:
Flag                  | Execution time (average of 3)
----------------------|------------------------------
None (current code)   | 25.5s
`-parallelism=16`     | 18.8s
`-parallelism=24`     | 15.7s
`-parallelism=32`     | 17.1s
Thus it appears that three times the number of logical cores results in
the most substantial reduction in time on average.
With this in mind, change the default parallelism used by these
Terraform commands.
> Increase parallelism of Terraform commands

- lib/geoengineer/cli/terraform_commands.rb
Setting the color to `light_white` makes it not appear in terminals with
white backgrounds. Since this is temporary anyway, remove the coloring
completely.
> Remove colorization from headings

- lib/geoengineer/resources/aws_iam_instance_profile.rb
As of version 0.9.3, Terraform deprecates `roles` in favor of `role`.
This manifests itself with warnings like:
* aws_iam_instance_profile.my-profile: "roles": [DEPRECATED] Use
`role` instead. Only a single role can be passed to an IAM
Instance Profile
Update our custom validation to expect the newer attribute name. This
breaks support for users using Terraform versions older than 0.9.3.
See https://github.com/hashicorp/terraform/pull/13130 for additional
context.
> Update required attribute for instance profiles from roles -> role

- lib/geoengineer/resources/aws_alb.rb
- lib/geoengineer/utils/aws_clients.rb
- spec/resources/aws_alb_spec.rb
Added a wrapper for ALB's and added some tests as well.
The ELB chose to enforce the name being present, which precludes the use
of the name prefix. In practice, that was fine, in part because the name
was then used as the terraform ID. With ALB's, the name is only part of
the ID, and the rest contains what looks to be some random value.
This means that the best way to keep track of the resource is via the
tags, however that means that an extra call is required to grab the
tags.
Added the usual resource tests.
> [New] Add AWS ALB to supported resources

- lib/geoengineer/resources/aws_alb_listener.rb
- lib/geoengineer/resources/aws_alb_listener_rule.rb
- lib/geoengineer/resources/aws_alb_target_group.rb
- lib/geoengineer/utils/aws_clients.rb
- spec/resources/aws_alb_listener_rule_spec.rb
- spec/resources/aws_alb_listener_spec.rb
- spec/resources/aws_alb_target_group_spec.rb
Add ability to codify listeners, rules, and target groups.
Opted not to codify the target group attachment, as that "resource" only
exists there is an instance described via the target health endpoint.
Also, I imagine those attachments will change too frequently to provide
much value being codified.
Added the usual tests.
> [New] Add other ALB Resources

- lib/geoengineer/resources/aws_customer_gateway.rb
- lib/geoengineer/resources/aws_route53_record.rb
- lib/geoengineer/resources/aws_vpn_connection.rb
The `GeoEngineer::Resource` base class defines a function named `type` which
returns the reource type. This however clashes with resources that have an
attribute named `type`. Currently, this happens with 3 objects:
* `aws_customer_gateway`
* `aws_route53_record`
* `aws_vpn_connection`
The problem that happens is an error setting the `type` attribute. It will throw
an `ArgumentError` saying `wrong number of attributes (1 given, 0 expected)`. On
all, the `type` is required, where not setting it would then result in a
validation error.
This simply adds function for each that will allow setting the value in the
attribute hash.
> [fix] Handle attributes named 'type' that clash with base functions

- lib/geoengineer/resources/aws_waf_ipset.rb
See #130 (specifically [this comment](https://github.com/coinbase/geoengineer/pull/130#pullrequestreview-48173134)) for reference.  Enforces a valid IP be submitted for an AWS WAF IPSet.
> Adding in forgotten validation on aws_waf_ipset

- lib/geoengineer/resources/aws_network_interface.rb
- spec/resources/aws_network_interface_spec.rb
This adds the Terraform `aws_network_interface` resource to create ENI's within
EC2. This allows specifying a single or multiple private IP addresses to an interface that can attached a machine to manage its internal IP address.
> Add aws_network_interface resource

- lib/geoengineer/resources/aws_route53_record.rb
- lib/geoengineer/resources/aws_route53_zone.rb
This adds additional fixes to Route53 handling, including proper handling for
zone FQDN handling to include the trailing dot in the terraform id, as well as
outputting the terraform state to handle importing zones attached to multiple
VPCs.
Also a number of updates to the record handling, including updating it to work
as remote resource and populate with existing data. It'll properly retrieve all
records across multiple pages, and also has necessary handling for trailing dot
handling.
On record values, Route53 seems a bit inconsistent with its trailing dot
handling. It seems to work with or without, however doesn't massage the data on
its end.
> Additional updates to support Route53 zones and records.

- lib/geoengineer/cli/terraform_commands.rb
As of 0.10, Terraform now requires a `terraform init` step before plan so it can fetch the `aws` provider plugin.
This is a result of them forking out the providers into separate repositories; they're no longer included in the `terraform` binary itself.
<https://github.com/hashicorp/terraform/blob/master/CHANGELOG.md#0100-august-2-2017>
Cheers,
Anthony
> Terraform 0.10+ requires a "terraform init" before plan

- lib/geoengineer/resources/aws_iam_role.rb
otherwise seeing one warning per iam_role
```
~ aws_iam_role.role1
force_detach_policies: "" => "false"
~ aws_iam_role.role2
force_detach_policies: "" => "false"
~ aws_iam_role.role3
force_detach_policies: "" => "false"
```
> default force_detach_policies on aws_iam_role to avoid fake diffs

- lib/geoengineer/resources/aws_route_table.rb
Fixes an issue pointed out in a comment by @palexvs where the subresource
validation had an invalid reference to `:cider_block`.
@brad-larson
> Fix reference to `cider_block` to `cidr_block`

- lib/geoengineer/resources/aws_kinesis_stream.rb
- spec/resources/aws_kinesis_stream_spec.rb
Right now, if a stream has more than 100 shards, it will be treated as
more than one remote resource. This fixes that, and has been been
confirmed locally.
> [Fix] Update Kinesis to handle large streams

- lib/geoengineer/resources/aws_alb.rb
- lib/geoengineer/resources/aws_alb_listener.rb
- lib/geoengineer/resources/aws_alb_target_group.rb
- spec/resources/aws_alb_listener_spec.rb
- spec/resources/aws_alb_spec.rb
- spec/resources/aws_alb_target_group_spec.rb
ALB Listeners don't support tags, so add `supports_tags?` => `false`
The `_geo_id` for ALB Target groups was quite naive, and would have
quickly run into conflicts. Since the resource supports tags, we'll use
that instead. Also updates the tests accordingly.
> [FIX] Update ALB Resources

- lib/geoengineer/resources/aws_vpn_connection_route.rb
After upgrading to the latest Terraform AWS provider, the `aws_vpn_connection_route` resource state was not being properly generated. Here, we explicitly set the state to the expected values.
> Updates aws_vpn_connection_route resource after AWS provider upgrade

- lib/geoengineer/resources/aws_route53_zone.rb
- spec/resources/aws_route53_zone_spec.rb
This fixes `aws_route53_zone` to include whether the zone is public or private
one belonging to a VPC in the `geo_id`. This helps in cases where the same
domain has two or more zones, such as a public one and a private one internal to
a VPC.
> Updates route53_zone to handle differentiating public/private zones.

- lib/geoengineer/resources/aws_emr_cluster.rb
- spec/resources/aws_emr_cluster_spec.rb
AWS allows you to create multiple clusters with the same name if the existing cluster is already terminated. Filter out terminated clusters so that Geo's resource finding doesn't fail when setting up and tearing down multiple clusters quickly.
This is especially necessary since AWS will keep these terminated clusters around for potentially weeks (looking around online, there is no officially documented timeframe).
> Ignore terminated EMR clusters

- lib/geoengineer/resources/aws_nat_gateway.rb
- spec/resources/aws_nat_gateway_spec.rb
AWS recently added tag support for NAT gateways. This PR forces NAT gateways to be declared using the Name tag as the `_geo_id` for NAT gateways
> Updates AwsNatGateway resource and specs

- lib/geoengineer/resources/aws_dynamodb_table.rb
- lib/geoengineer/templates/json_rest_api.rb
Calculating the TTL is very expensive due to the AWS API, so instead of calculating it, we will just not support updating it till terraform refresh works for it. 
Linked issue https://github.com/hashicorp/terraform/issues/16766
Also: minor fix for rest_api template.
> [Hack] dynamodb TTLs not supported for updating

- lib/geoengineer/cli/terraform_commands.rb
When we added calls to `terraform init` and `terraform refresh` in 0df52fdb and b065741d, respectively, we forgot to include the `-no-color` flag for these commands. This results in output erroneously containing ANSI escape sequences in scenarios where it is not desired.
> Fix --no-color flag

- lib/geoengineer/resources/aws_rds_cluster_parameter_group.rb
- spec/resources/aws_rds_cluster_parameter_group_spec.rb
This modifies the RDS Cluster parameter group to pull the DB cluster
parameter groups, not the DB parameter groups that happen to be for
aurora DB instances.
> [FIX] Update the RDS Cluster Param Group

- CONTRIBUTING.md
- LICENSE
Ensures we are referencing our code of conduct.
---
The license is the same, we're just include the verbatim text so that GitHub correctly identifies it as an Apache-2.0-licensed project.
This also updates the copyright year to 2018.
---
> Update contribution guidelines and license year

- geoengineer.gemspec
- lib/geoengineer.rb
- lib/geoengineer/environment.rb
- lib/geoengineer/resources/github_issue_label.rb
- lib/geoengineer/resources/github_membership.rb
- lib/geoengineer/resources/github_repository.rb
- lib/geoengineer/resources/github_repository_collaborator.rb
- lib/geoengineer/resources/github_team.rb
- lib/geoengineer/resources/github_team_membership.rb
- lib/geoengineer/resources/github_team_repository.rb
- lib/geoengineer/utils/github_client.rb
We want to allow GeoEngineer to be used to codify resources in GitHub organizations on the public GitHub as well as GitHub Enterprise.
This PR is lacking tests but works (I've used it to great effect in a project).
The main gotcha is that if you are configuring multiple organizations in a GitHub Enterprise instance, you'll have multiple providers which you'll need to reference via their alias in _every_ resource, e.g.
```ruby
env.provider('github') {
organization 'org-a'
self['alias'] = 'org-a'
}
env.provider('github') {
organization 'org-b'
self['alias'] = 'org-b'
}
env.resource('github_team', 'org-a-blue-team') {
name 'blue'
provider 'github.org-a'
}
env.resource('github_team', 'org-b-red-team') {
name 'red'
provider 'github.org-b'
}
```
We want to allow GeoEngineer to be used to codify …
> Add support for most GitHub resources

- geoengineer.gemspec
- lib/geoengineer/resources/aws_cloudfront_distribution.rb
- lib/geoengineer/resources/aws_eip.rb
- lib/geoengineer/resources/aws_route_table_association.rb
- spec/resources/aws_cloudfront_distribution_spec.rb
- spec/resources/aws_eip_spec.rb
AND allowed route table to decide on _geo_id
> [Update] updated AWS SDK, EIP now supports tags using as _geo_id

- lib/geoengineer/resources/aws_lb.rb
- lib/geoengineer/resources/aws_lb_target_group.rb
This adds the default values for some of the extended attributes on ALBs
and ALB target groups. This prevents erronous plan updates, such as
changing idle_timeout from `""` to `"60"`. That is the default value,
but since it wasn't retrieved by Terraform, it didn't realize it was the
already configured value.
> Added default extended attributes for ALB and Target Groups

- lib/geoengineer/resources/aws_lb_target_group.rb
When generating a plan where there were a lot of load balancer target groups defined, the AWS SDK would complain that we can only fetch 20 resources at a given time.
This required two fixes: one where we page through the result set when fetching all target groups, and another where we fetch tags specifying the explicit ARNs for those target groups. In both cases, we only fetch 20 resources at a time.
We opted to fetch the tags in parallel because we know the ARNs ahead of time, whereas when fetching the initial list of load balancers we have to perform this in serial.
> Fix fetching of more than 20 ALB target groups

- lib/geoengineer/resources/aws_lb.rb
- spec/resources/aws_lb_spec.rb
Previously, environments with > 20 ALBs or NLBs would fail to plan. This PR generalized the process of fetching LBs so that these larger environments can be planned
> Fetch ALBs to not exceed the limits of the AWS LB API

- lib/geoengineer/resources/aws/iam/aws_iam_saml_provider.rb
- spec/resources/aws_iam_saml_provider_spec.rb
aws_iam_saml_provider terraform_id must be aws arn
As specified in terraform's
[aws_iam_saml_provider](https://github.com/terraform-providers/terraform-provider-aws/blob/master/aws/resource_aws_iam_saml_provider.go#L62)
> aws_iam_saml_provider: dont support tags + support terraform / geo id

- lib/geoengineer/resources/aws/vpc/aws_vpc_ipv4_cidr_block_association.rb
- spec/resources/aws_vpc_ipv4_cidr_block_association_spec.rb
https://www.terraform.io/docs/providers/aws/r/vpc_ipv4_cidr_block_association.html
There are quite a few rules about what additional ranges on a vpc can look [like](https://docs.aws.amazon.com/vpc/latest/userguide/VPC_Subnets.html#add-cidr-block-restrictions).
I didn't look at every resource, but I couldn't find any example of validating based on the attribute of an associated resource. In this case we need the primary cidr of the vpc. It seemed like it was worth the effort because most of the time I would expect that vpc and aws_vpc_ipv4_cidr_block_association resources get codified together. If the vpc_id attribute of the aws_vpc_ipv4_cidr_block_association resource isn't a ref to another `GeoEngineer::Resource` then the complicated validation is just skipped. 
This may be overly …
> Add support for aws_vpc_ipv4_cidr_block_association resources

- lib/geoengineer/cli/terraform_commands.rb
Looks like there were still a couple backdoors where geoengineer
could exit without using the proper exit codes. Closed them.
> Exit with the proper exit code even for unusual failures

- lib/geoengineer/resources/aws/rds/aws_rds_cluster_instance.rb
This removes the validation to require `name`, `username`, and `password` fields
from `aws_rds_cluster_instance`. These are set on `aws_rds_cluster` rather than
on the instance itself.
> Removes invalid fields from aws_rds_cluster_instance

- .rubocop_todo.yml
- spec/spec_helper.rb
These are breaking the build and in this particular case aren't useful.
> Fix RuboCop warnings

- lib/geoengineer/resource.rb
Fixes a bug where a return of nil should be assumed no resource, but errors
> [Fix] fix return nil from individual remote resource

- lib/geoengineer/resources/aws/vpc/aws_dx_connection.rb
- lib/geoengineer/utils/aws_clients.rb
- spec/resources/aws_dx_connection_spec.rb
This adds the `aws_dx_connection` resource, which is used to set up Direct
Connect. Overall it is a simple object, but will have following resources to add
once my existing DC request is activated within AWS.
> Add aws_dx_connection resource

- lib/geoengineer/cli/geo_cli.rb
- lib/geoengineer/cli/terraform_commands.rb
- lib/geoengineer/cli/test_cmd_stubs.rb
When the `geo test` command is run this allows more stubbing as some AWS stubs do not properly work with no expected return.
> [Fix] better stubbing for `geo test` command

- lib/geoengineer/provider.rb
In multi-account, multi-region scenarios, it is helpful to make use of
the assume_role block of the aws provider. Other providers may have sub-
resources also.
> Add support for SubResources on Providers

- lib/geoengineer/resources/aws/rds/aws_rds_cluster_endpoint.rb
- spec/resources/aws_rds_cluster_endpoint_spec.rb
Implement the AwsRdsClusterEndpoint class to support creating custom
endpoints with AWS Aurora.
Used locally in staging environment for testing it works as expected.
> Add support for aws_rds_cluster_endpoint

- lib/geoengineer/resources/aws/api_gateway/aws_api_gateway_resource.rb
Currently, geoengineer sets the `parent_id` on all API Gateway resources to the
root resource (that is, '/'). This forces all APIs into a flat structure when
the more natural structure is a hierarchical organization.
This small change makes it so that users can set the `parent_id` to something
other than the root resource, allowing hierarchical organization of API
resources.
> Add ability to nest API Gateway resources.

- lib/geoengineer/resources/aws/api_gateway/aws_api_gateway_method_settings.rb
- lib/geoengineer/resources/aws/api_gateway/aws_api_gateway_rest_api.rb
- spec/resources/aws_api_gateway_method_settings_spec.rb
Currently missing from Geoengineer is the ability to configure the settings on
an API Gateway. This change adds a new resource, `AwsApiGatewayMethodSettings`,
that maps to the Terraform `api_gateway_method_settings` resource. Has been
tested against actual API Gateway resources.
> Add Support For aws_api_gateway_method_settings Terraform Resource

- lib/geoengineer/resources/aws/api_gateway/aws_api_gateway_rest_api.rb
Add the `_policy_file` shorthand for `aws_api_gateway_rest_api` resources to
make defining the resource policy simpler. Currently you have to write
something like the following:
```
policy _json_file(:policy, '<PATH>')
```
After this change you would simply write
```
_policy_file '<PATH>'
```
> Add _policy_file Shorthand For API Gateway Rest API

- lib/geoengineer/resources/aws/api_gateway/aws_api_gateway_method_settings.rb
Previously we were using the stages ID when what is actually requested is the
name of the stage. This change fixes this bug and also allows for users to
optionally specify the stage name themselves.
> Fix Stage Name Bug In AwsApiGatewayMethodSettings

- lib/geoengineer/gps/gps.rb
This removes a likely errant pry require statement. Currently, pry is simply
listed as a dev dependency, however part of GPS was importing it directly.
> Remove an errant pry require statement.

- lib/geoengineer/resources/aws/rds/aws_rds_cluster_endpoint.rb
- spec/resources/aws_rds_cluster_endpoint_spec.rb
This updates the handling for the terraform_id and geo_id in the
`aws_rds_cluster_endpoint` resource. This was being set to the cluster's
identifier, however this wouldn't work when using the resource for custom
endpoints, as it would create the resources, but then on the next run see them
as missing and then fail on the apply.
The resource can only really be used for custom endpoints and not for the built
in default reader/write, from the looks of the Terraform code. On those, AWS
doesn't return a `db_cluster_endpoint_identifier`, but those ones can't really
be altered within Terraform anyway.
> Update terraform_id/geo_id handling on aws_rds_cluster_endpoint

- lib/geoengineer/resources/aws/organizations/aws_organizations_account.rb
- lib/geoengineer/resources/aws/organizations/aws_organizations_organization.rb
- lib/geoengineer/resources/aws/organizations/aws_organizations_policy.rb
- lib/geoengineer/resources/aws/organizations/aws_organizations_policy_attachment.rb
- lib/geoengineer/utils/aws_clients.rb
- spec/resources/aws_organizations_account_spec.rb
- spec/resources/aws_organizations_organization_spec.rb
- spec/resources/aws_organizations_policy_attachment_spec.rb
- spec/resources/aws_organizations_policy_spec.rb
This adds support for the following resource types:
* aws_organizations_organization
* aws_organizations_account
* aws_organizations_policy
* aws_organizations_policy_attachment
These are used to create a child account within an AWS Organization
programmatically, as well as to create service control policies within the
organization which define a top level definitions of actions that are allowed
within child accounts.
> Add support for aws_organizations_* objects

- lib/geoengineer/resources/aws/iam/aws_iam_account_alias.rb
- lib/geoengineer/resources/aws/iam/aws_iam_group_policy.rb
- lib/geoengineer/resources/aws/iam/aws_iam_user_policy.rb
- lib/geoengineer/resources/aws/organizations/aws_organizations_account.rb
- lib/geoengineer/utils/has_validations.rb
- spec/resources/aws_iam_account_alias_spec.rb
This adds a few additional resources around IAM that I was using when
setting up some Organizations entries.
First, adds the aws_iam_account_alias resource, which is used to set up
those nicely named account shortcuts.
Second, adds `aws_iam_{group,user}_policy` to set policies directly on a
user or group. We already had the resource for role policy, these were
literal copy and pastes. The role resource had no tests, potentially
since its an annoying chain to fetch the resources.
Third, updates `aws_organizations_account` to ignore changes for
iam_user_access_to_billing. The field isn't retrievable after creating,
so it will always show as needing to change but requires destroying the
account.
Finally, updated the validation message when a policy is too large to
include the name of the …
> Adds some additional resources around IAM

- lib/geoengineer/resources/aws/vpc/aws_dx_hosted_private_virtual_interface.rb
- lib/geoengineer/resources/aws/vpc/aws_dx_hosted_private_virtual_interface_accepter.rb
- lib/geoengineer/resources/aws/vpc/aws_dx_lag.rb
- lib/geoengineer/resources/aws/vpc/aws_dx_private_virtual_interface.rb
- spec/resources/aws_dx_hosted_private_virtual_interface_accepter_spec.rb
- spec/resources/aws_dx_hosted_private_virtual_interface_spec.rb
- spec/resources/aws_dx_lag_spec.rb
- spec/resources/aws_dx_private_virtual_interface_spec.rb
This adds additional support for link aggregation groups (LAGs) and private
virtual interfaces.
The hosted virtual interfaces are two support interfaces across accounts, where
one account own the Direct Connect hook up, but is linking to a VPC in another
account. The "acceptor" resource is used on the side with the VPC being
connected to.
> Adds support for additional Direct Connect resources.

- lib/geoengineer/resources/aws/api_gateway/aws_api_gateway_resource.rb
- lib/geoengineer/resources/aws/api_gateway/helpers.rb
Geoengineer does not recognize API Gateway resources it has created because it does not consider the parent when recreating the geo ids of remote resources. This PR changes the geo id scheme to be the full resource path delimited by double colons, so geo is guaranteed to be able to relate remote resources to defined resources while ensuring that resources with the same name but different parents do not conflict.
> API Gateway resource geo ids should be based on the resource's full path

- lib/geoengineer/gps/gps.rb
- spec/gps/gps_spec.rb
- spec/gps/test_nodes.rb
- spec/spec_helper.rb
This refactors the ability of GPS to handle meta nodes which in turn
build other meta nodes.
It does so in a recursive manner, whereas the current approach was
limited to a depth of 3.
It also adds tests for this behavior.
> [FIX] Allow for meta meta nodes

- .rubocop.yml
- lib/geoengineer/gps/gps.rb
- lib/geoengineer/gps/node.rb
- spec/gps/gps_spec.rb
- spec/gps/test_nodes.rb
This adds the ability to use node references with a GPS file.
Often it is useful to refer some specific attribute of a resource
created by a node, for example a KMS key ARN.
Currently, you can only reference the KMS node, and so other consuming
nodes would have to hardcode the attribute extraction logic.
This works ok, but breaks down when used for things like policies, where
the reference is being substituted into a JSON document. For this, the
user needs to be explicit about which resource and which attribute.
This PR adds that capability, with the syntax:
`<project>:<environment>:<configuration>:<node_type>:<node_name>#<resource>.<attribute>`
And generates the appropriate terraform reference.
If no resource is specified, it returns the node itself. This can be
useful if you need to …
> [NEW] Add dereferencing

- lib/geoengineer/resource.rb
- lib/geoengineer/resources/aws/db/aws_db_instance.rb
- lib/geoengineer/resources/aws/db/aws_db_parameter_group.rb
This adds pagination to the aws_db_instance and aws_db_parameter_group
resources, which were previously capped at 100.
Does this via a `_paginate` helper on `Resource`
> [FIX] Add pagination

- lib/geoengineer/resources/aws/api_gateway/aws_api_gateway_model.rb
- lib/geoengineer/resources/aws/api_gateway/helpers.rb
- spec/resources/aws_api_gateway_model_spec.rb
This commit completes the implementation of `AwsApiGatewayModel`, previously
this class was missing the `_fetch_remote_resources` implementation and this
produced a `NotImplementedError` when attempting to run `geo plan` against a
plan with such a resource.
It includes two new helper methods, `_fetch_remote_rest_api_models` and
`_remote_rest_api_models` to aid in the implementation of
`_fetch_remote_resources`.
> Complete AwsApiGatewayModel Interface

- lib/geoengineer/cli/terraform_commands.rb
Often I am running a plan, and it triggers an error:
```
This plan would destroy resource X, but it has prevent destroy = true.
Please fix
```
Then I have to go into the `tmp/environment` directory, modify the
`terraform.tf.json` file to allow destroy on those resources, and
re-run just the terraform plan command from the `./geo plan` output.
Annoying.
This will let me append `--allow-destroy` to a `./geo plan` and more
easily let me see why my plan is failing.
INFRA-2979
> [NEW] Add `--allow-destroy` option on plan

- lib/geoengineer/resources/aws/vpc/aws_dx_hosted_private_virtual_interface_accepter.rb
- spec/resources/aws_dx_hosted_private_virtual_interface_accepter_spec.rb
This fixes the class name for the
`aws_dx_hosted_private_virtual_interface_accepter` resource. The ruby
file was named `accepter` and all, however the class name was previously
`acceptor`. This was incorrect and didn't catch until looked at it very
closely. :smile:
> Fix class name for resource on hosted Direct Connect interfaces

- lib/geoengineer/gps/gps.rb
- spec/gps/gps_spec.rb
Currently, an invalid extra argument is being passed to `find` method. This
results in the following error:
```
ArgumentError: wrong number of arguments (given 2, expected 1)
```
This adds a test to check for this regression in the future and fixes it.
> Fix ArgumentError With Finder

- lib/geoengineer/resources/aws/api_gateway/aws_api_gateway_model.rb
The current terraform state is missing the `name` and `rest_api_id` attributes
and this causes issues with Terraform. This change ensures that these appear in
the tfstate data as expected.
> Fix Terraform State For API Gateway Models

- .gitignore
- lib/geoengineer/resources/aws/api_gateway/aws_api_gateway_request_validator.rb
- lib/geoengineer/resources/aws/api_gateway/helpers.rb
- spec/helpers/api_gateway_helpers.rb
- spec/resources/aws_api_gateway_model_spec.rb
- spec/resources/aws_api_gateway_request_validator_spec.rb
Add a new API Gateway resource that will allow defining and using
aws_api_gateway_request_validators.
> Add Support For aws_api_gateway_request_validator

- lib/geoengineer/gps/finder.rb
- lib/geoengineer/gps/gps.rb
- spec/gps/finder_spec.rb
Right now, both `dereference` and `dereference!` error if nothing is
found. This will conform to the `!` as broadly used in the Ruby
community, and also allow us to use `dereference` in all environments
for gps partials.
>  [REFACTOR] Only raise on `dereference!`

- lib/geoengineer/gps/yaml_tag.rb
- spec/gps/yaml_tag_spec.rb
In order for optimization to work, we need to be able preserve the yaml
tags.
This should do that.
> [FIX] Add to_yaml to Tag objects

- lib/geoengineer/resources/aws/api_gateway/helpers.rb
- spec/resources/aws_api_gateway_request_validator_spec.rb
There was a bug in `_fetch_remote_rest_api_request_validators` where instead of
the final request validator Hash object being returned, the `_geo_id` string for
the request validator was returned. This was causing downstream issues in
provisioning API Gateways with request validators.
> Fix Request Validator Remote Fetch Bug

- lib/geoengineer/gps/yaml_tag.rb
- spec/gps/yaml_tag_spec.rb
We need to ensure that if you have a `!ref` or more likely, a `!sub`
tag mixed in with other normal strings, integers, etc... that it doesn't
error, and allows for comparisons based on the tag value.
> [FIX] Make sort type agnostic

- lib/geoengineer/gps/node.rb
Its used downstream, and generally just nice to keep track of the attributes before expansion.
> Re-add this method

- lib/geoengineer/resources/aws/route53/aws_route53_zone.rb
Terraform updated their syntax to define the VPC peering noted here:
https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md
The Geo ID for Route53 Zone used to rely on the old, now deprecated
syntax. This updates the GeoID logic to use the syntax.
> [FIX] Update GeoID for Route53 Zone

- lib/geoengineer/resources/aws/api_gateway/aws_api_gateway_model.rb
- lib/geoengineer/resources/aws/api_gateway/aws_api_gateway_request_validator.rb
Currently, terraform is unable to recognize `aws_api_gateway_model` and
`api_gateway_request_validator` resources because their primary attributes are
incorrect, namely they are using a reference to the rest_api object instead of
the terraform_id of the rest API object. This was causing terraform to attempt
to repeatedly recreate resources that already existed.
This change fixes this issue by using the correct identifier for these primary
attributes.
> Fix: API Gateway Resource Terraform State Issues

- lib/geoengineer/gps/node.rb
Which would set initial_attributes to the fully expanded attributes,
which is _not_ what we want.
I swear I had removed that already. Oh well.
> [FIX] Remove second call to initial_attributes

- lib/geoengineer/resources/aws/api_gateway/aws_api_gateway_gateway_response.rb
- lib/geoengineer/resources/aws/api_gateway/helpers.rb
- spec/helpers/api_gateway_helpers.rb
- spec/resources/aws_api_gateway_gateway_response.rb
Add support for customizing gateway responses via the `aws_api_gateway_gateway_response`
resource.
> Add aws_api_gateway_gateway_response Resource Support

- .gitignore
- lib/geoengineer/resources/aws/api_gateway/aws_api_gateway_authorizer.rb
- lib/geoengineer/resources/aws/api_gateway/helpers.rb
- spec/helpers/api_gateway_helpers.rb
- spec/resources/aws_api_gateway_authorizer_spec.rb
Completes the `_fetch_remote_resources` and `to_terraform_state` methods for the `AwsApiGatewayAuthorizer` 
Was able to successfully plan the creation of an authorizer using this branch locally.
> Complete AW API Gateway Authorizer

- lib/geoengineer/resources/aws/api_gateway/aws_api_gateway_method.rb
- spec/resources/aws_api_gateway_method_spec.rb
Applies are failing for api gateway methods that specify an authorization type that requires an authorizer id. Geo wasn't previously setting an authorizer id in the to_terraform_state method.
> Set the authorizer id in terraform if it exists

- lib/geoengineer/gps/yaml_tag.rb
Previously, the `!sub` tag required `{{value}}`, and would fail with
`{{ value }}`. That kinda sucks. So I fixed it.
> [FIX] Allow sub tag to work with spaces

- lib/geoengineer/resources/aws/elasticache/aws_elasticache_subnet_group.rb
It seems Terraform requires the name attribute to be present in order to
refresh the state.
> [FIX] Allow elasticache_subnet_group to plan

- spec/resources/aws_vpc_endpoint_service_spec.rb
Tests were broken when adding aws_vpc_endpoint_service.
> Fix tests related to disabling line length rules in a spec.

- lib/geoengineer/resource.rb
If a provider "aws" is selected it should be selected by the resource when fetching remote resources.
e.g.
```
env.provider("aws") {
region "us-west-1"
}
```
should be the default region for all resources without explicitly defined provider
> [Fix] Select the default provider if not explictly defined

- lib/geoengineer/resources/aws/lb/aws_load_balancer_listener_policy.rb
- spec/resources/aws_load_balancer_listener_policy_spec.rb
The AWS load balancer listener policy resource allows GeoEngineer to set SSL negotiation policies on an ELB's listener. The identifying information for an ELB's listener is combination of the load balancer's name and the load balancer port.
> adding aws load balancer listener policy and tests

- lib/geoengineer/resources/aws/vpc/aws_vpc_peering_connection_accepter.rb
- spec/resources/aws_vpc_peering_connection_accepter_spec.rb
This adds the resource for aws_vpc_peering_connection_accepter, which is needed
in some use cases around cross region peering, where using the non-accepter
resource will create a duplicate resource which enters the failed state once
created.
With this resource, you need to know the connection ID from the requestor side
already, but it is mostly used for Terraform to be able to find and update the
pre-created resource that is pending acceptance.
> Adds resource for awss_vpc_peering_connection_accepter

- lib/geoengineer/gps/constants.rb
- lib/geoengineer/gps/finder.rb
- spec/gps/constants_spec.rb
This allows values which equal `false` to be dereferenced.
It also allows `?` to be used in constant names.
> [FIX] Allow falsey values to be dereferenced

- lib/geoengineer/resources/aws/ec2/aws_key_pair.rb
This adds a very simple resource for `aws_key_pair`, used to create public keys
for instances in EC2.
The resource doesn't have any tests, since it doesn't leverage any remote
functionality or anything. All there really is on them is the key name and
public key.
This is ignoring changes to `public_key` and `fingerprint`, so any changes to
the key will require you to delete it to apply it. Having either one unignored
would result in it constantly thinking it needed to recreate the resource.
AWS doesn't return the public key, only the fingerprint. We could build the
fingerprint from the public key, and not ignore the fingerprint, but generating
the fingerprint doesn't appear possible with the stdlib in Ruby. It can be done
with `Net::SSH`, but that is adding a dependency for a scarcely used …
> Add resource for aws_key_pair

- lib/geoengineer/environment.rb
- lib/geoengineer/resource.rb
This didn't work because `local_resource` would never be set when running `fetch_remote_resources`, resulting in all resources being considered "uncodified".
I'm not sure where this broke, but I imagine it has something to do with the GPS migration given the overall required to support it.
> Fix uncodified resource calculation

- lib/geoengineer/resources/aws/db/aws_db_instance.rb
- lib/geoengineer/resources/aws/db/aws_db_parameter_group.rb
The `aws_db_instance` and `aws_db_parameter_group` resources were returning Aurora-related resources in addition to vanilla RDS resources.
This throwing off our codification metric as the Aurora-related resources would appear as remote resources but wouldn't have a corresponding local resource.
Fix by filtering out any engine/family mentioning "aurora".
> Filter out Aurora-related databases and parameter groups

- lib/geoengineer/resource.rb
- spec/resource_spec.rb
This allows us to ignore classes of resources matching a certain name, which is useful as we move to more resource types being managed outside of code.
> Allow ignoring resources by regex

- lib/geoengineer/resources/aws/db/aws_db_parameter_group.rb
- lib/geoengineer/resources/aws/kinesis/aws_kinesis_firehose_delivery_stream.rb
The ruby AWS SDK automatically paginates over resources, remove custom logic. Firehose delivery streams do support tags. We have to use aurora type db parameter groups as rds_cluster_parameter_groups dont support the same feature set.
> Fixes for aws_kinesis_firehose_delivery_stream and aws_db_parameter_group

- lib/geoengineer/resources/aws/dynamodb/aws_dax_cluster.rb
- lib/geoengineer/resources/aws/dynamodb/aws_dax_parameter_group.rb
- lib/geoengineer/resources/aws/dynamodb/aws_dax_subnet_group.rb
- lib/geoengineer/utils/aws_clients.rb
- spec/resources/aws_dax_cluster_spec.rb
- spec/resources/aws_dax_parameter_group_spec.rb
- spec/resources/aws_dax_subnet_group_spec.rb
Add support for resources related to AWS DAX.
The translation was relatively straightforward. We borrowed implementations from `aws_rds_cluster`, `aws_db_parameter_group`, and `aws_elasticache_subnet_group`.
---
---
---
> Add DAX resources

- lib/geoengineer/resource.rb
- spec/resource_spec.rb
This PR merges the `tags` subresource into a single hash for the `terraform.json` which is required by terraform v0.12.0 but is backwards compatible with at least v0.11
> [Fix] v12 terraform requires tags be a single hash

- lib/geoengineer/resources/aws/kinesis/aws_kinesis_firehose_delivery_stream.rb
Turns out the aws-sdk doesn't auto paginate for all resources.
> Reverts a bug introduced by removing pagination.

- lib/geoengineer/resources/aws/efs/aws_efs_mount_target.rb
- spec/resources/aws_efs_mount_target_spec.rb
The AWS ruby sdk function describe_mount_targets doesn't return a list of all mount targets. Instead you need to provide the file_system_id for which you want to retrieve all mount targets, which requires a bit of logical refactoring.
> Improve support for efs mount_targets

- lib/geoengineer/resources/aws/pinpoint/aws_pinpoint_app.rb
- lib/geoengineer/utils/aws_clients.rb
This adds support for defining Pinpoint applications/projects (AWS uses
the names interchangibly, it seems). This was a request to work on
codifying some of the existing resources and move away from manually
configuring them.
> Adds support for aws_pinpoint_app resource.

- lib/geoengineer/gps/finder.rb
- lib/geoengineer/gps/gps.rb
This allows projects to be multi-layered deep e.g.
`/projects/test/example/ruby/service.gps.yml` will have a project name of `example/ruby/service`
Also using a hash for node lookup saves a few seconds.
> [Fix] allow projects to be sub-folders, speed improvement on node dereference

- lib/geoengineer/gps/node.rb
Through profiling it turns out ~10% of `geo test` time is spent in
node_id - this memoization saves 4s on the 40s test execution time
> Memoize node_id

- lib/geoengineer/resources/aws/lb/aws_alb_target_group_attachment.rb
- lib/geoengineer/resources/aws/lb/aws_lb_listener_rule.rb
- lib/geoengineer/resources/aws/lb/aws_lb_target_group.rb
- spec/resources/aws_alb_target_group_attachment_spec.rb
This is a work in progress for adding support for ALB listeners with routing rules.
**Changes**
- Add resource for target group attachments
- Disable tag and name validation for listener rules
- Split validation for lambda and instance target groups
**TODO**
> Add support for alb target group attachments

- geoengineer.gemspec
- lib/geoengineer.rb
- lib/geoengineer/resources/postgresql/postgresql_database.rb
- lib/geoengineer/resources/postgresql/postgresql_extension.rb
- lib/geoengineer/resources/postgresql/postgresql_role.rb
- lib/geoengineer/resources/postgresql/postgresql_schema.rb
- lib/geoengineer/utils/postgres_client.rb
- lib/geoengineer/utils/postgresql_client.rb
- spec/resources/postgresql_database.rb
- spec/resources/postgresql_extension.rb
- spec/resources/postgresql_role.rb
- spec/resources/postgresql_schema.rb
This PR adds support for configuring postgresql databases, extensions, roles, and schemas through geoengineer via the [postgresql provider](https://www.terraform.io/docs/providers/postgresql/index.html).
> Add support for the postgresql provider

- lib/geoengineer/resource.rb
- lib/geoengineer/resources/aws/msk/aws_msk_cluster.rb
- lib/geoengineer/resources/aws/msk/aws_msk_configuration.rb
- spec/resources/aws_msk_cluster_spec.rb
- spec/resources/aws_msk_configuration_spec.rb
The way `_terraform_id` was initialized previously caused failures on `./geo plan` and `./geo apply`.
* Changed how `_terraform_id` is set to fix plan failures. I.e. `_terraform_id: msk_config[:arn]`.
* Changed tests to reflect the above fix.
* Added more validation for `aws_msk_cluster` attributes based on what AWS requires when creating an MSK cluster through a console.
* Optional (in Terraform) `encryption_info.encryption_in_transit.client_broker` is now required because of inconsistency between Terraform and AWS SDK defaults for this attribute. This is done to remove ambiguity.
Both `aws_msk_cluster` and `aws_msk_configuration` were manually tested in dev environment with `./geo plan` and `./geo apply`.
> Bug fixes for aws_msk_cluster and aws_msk_configuration

- lib/geoengineer/templates/users_with_policies.rb
Running geo from bin/geo causes this issue. After removing the require it works.
```
➜  bin  git:(master) ✗ ./geo help
Traceback (most recent call last):
9: from ./geo:3:in `<main>'
8: from ./geo:3:in `require_relative'
7: from /Users/aartiparikh/github.com/aarti/geoengineer/lib/geoengineer.rb:45:in `<top (required)>'
6: from /Users/aartiparikh/github.com/aarti/geoengineer/lib/geoengineer.rb:45:in `each'
5: from /Users/aartiparikh/github.com/aarti/geoengineer/lib/geoengineer.rb:45:in `block in <top (required)>'
4: from /Users/aartiparikh/.rbenv/versions/2.5.5/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
3: from /Users/aartiparikh/.rbenv/versions/2.5.5/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
2: from …
```
> remove require as it is a circular dependency to this gem

- lib/geoengineer/cli/geo_cli.rb
Some users are getting issues when not using AWS (bundle exec geo test) and GEO_ENV is not set, so it defaults to staging. But we use development, not staging - therefore, their CLI breaks.
This will improve their productivity by defaulting to the right environment without needing them to configure it.
> [chore] rename default GEO_ENV -> development

- geoengineer.gemspec
The current`aws-sdk` version is missing `list_configurations` method in `Aws::Kafka::Client` class. This method is used in [aws_msk_configuration](https://github.com/coinbase/geoengineer/blob/master/lib/geoengineer/resources/aws/msk/aws_msk_configuration.rb) in `_fetch_remote_resources`.
Geoengineer now uses major version of `aws-sdk`, just like [aws-sdk-ruby](https://github.com/aws/aws-sdk-ruby) docs suggest.
`bundle exec rspec` passes all tests.
> Use major version when expressing a dependency on aws-sdk

- lib/geoengineer/resources/aws/db/aws_db_instance.rb
From looking over the AWS documentation, AllowMajorVersionUpgrade is a field on
the ModifyDBInstance action, however it is not a field on DBInstance, which is
returned with DescribeDBInstances. The field isn't persisted at all, and is
simply used as a necessary check when also updating the EngineVersion.
From the documentation, the field needs to be set to true when also changing
EngineVersion.
In Geoengineer, the field always shows up in plans as `"" => "false"`. This is
becaues it is always initialized to an empty string in Terraform, and not set to
a specific value at all on refresh.
This updates Geoengineer to populate it with `false` in `to_terraform_state` so
it begins with a blank/default value in Terraform.
> Update aws_db_instance to initialize allow_major_version_upgrade

- lib/geoengineer/resources/aws/certificate_manager/aws_acmpca_certificate_authority.rb
- lib/geoengineer/utils/aws_clients.rb
- spec/resources/aws_acmpca_spec.rb
This adds the ACMPCA resource to geoengineer. 
- The geo_id is a combination of the Type::Common_name.
- The ACMPCA resource does not include an easy to use name or identifiable/unique attribute that could have been used to create the geo_id so it had to be a combination.
- AWS keeps the deleted ACMPCA's around for 30 days and therefore they have been filtered out when fetching remote_resources.
- Tags were also considered for geo_id and could not be used since they are not returned during ListCertificateAuthorities call in AWS. AWS is moving away from making tags available in the same call and a seperate call for each resource called ListTags would have to be called if tags were to be used.
- An initialize resource test was added to verify that the geo_id is created correctly. 
- The nil …
> Add the ACMPCA resource to geoengineer

- geoengineer.gemspec
- lib/geoengineer/resources/aws/certificate_manager/aws_acmpca_certificate_authority.rb
Given Ruby 2.3 reached end of life in March 2019 (https://www.ruby-lang.org/en/news/2019/03/31/support-of-ruby-2-3-has-ended/), changing the minimum required Ruby version to 2.5 so we could use the safe navigation operator (&.).
> change min ruby requirement to 2.5 and use optional safe

- .gitignore
- examples/example_acmpca.rb
- examples/example_acmpca_certificate.rb
- lib/geoengineer/resources/aws/certificate_manager/aws_acm_certificate_private_ca.rb
- lib/geoengineer/utils/aws_clients.rb
- spec/resources/aws_acm_certificate_private_ca_spec.rb
ACM certificate resource to create certificates for private CA. 
AWS provides 3 options for issuing certificates, we are codifying ACM#request_certificate. 
1. Private CA issued cert 
a) ACMPCA#issue_certificate ( Terraform does not support this at the moment)
b) ACM#request_certificate(Private CA arn is required) (AWS managed renewal)
2. Import a Cert into ACM to be managed ACM#import_certificate
3. Amazon Issued cert ACM#request_certificate
> The ACM certificate resource for private CA issued certificates

- lib/geoengineer/resources/aws/vpc/aws_security_group.rb
- spec/resources/aws_security_group_spec.rb
Terraform docs for `ingress.protocol` at time of writing specify:
> protocol - (Required) The protocol. If you select a protocol of "-1" (semantically equivalent to "all", which is not a valid value here), you must specify a "from_port" and "to_port" equal to 0. If not icmp, tcp, udp, or "-1" use the protocol number
https://www.terraform.io/docs/providers/aws/r/security_group.html#protocol
This is confusing because Terraform itself doesn't prevent you from creating an ingress rule like:
ingress {
protocol -1
to_port 53
from_port 53
}
It should fail in this case, but doesn't. Make our validations fail loudly instead.
> Add validation for security groups with bad protocol/port settings

- lib/geoengineer/resources/aws/certificate_manager/aws_acmpca_certificate_authority.rb
- spec/resources/aws_acmpca_spec.rb
Nested blocks certificate_authority_configuration & subject are lists so they cannot be a subresources.
For context:
https://github.com/terraform-providers/terraform-provider-aws/blob/master/aws/resource_aws_acmpca_certificate_authority.go#L553
> Nested block certificate_authority_configuration is a list 

- lib/geoengineer/cli/geo_cli.rb
- lib/geoengineer/cli/terraform_commands.rb
This change allows the commands to be exported without adding a .geo.rb file.
> Update the CLI to export the graph and diff command.

- lib/geoengineer/resources/aws/s3/aws_s3_bucket_object.rb
This leads to issues when defining both an s3 bucket and s3 bucket object
> Change s3 bucket object terraform id to not conflict with bucket

- lib/geoengineer/resources/aws/api_gateway/helpers.rb
Raise the fetch limit for api gateways to 500 to quickly work around not fetching results via pagination. This mitigates not fetching all API gateways until we properly fix this bug.
> Fetch more API gateways per request

- lib/geoengineer/gps/constants.rb
- spec/gps/constants_spec.rb
This supports "!ref constant:*:account_id". 
This is useful for building a list across common constants across many environments. For example, you might want to get all cidr blocks across all environments.
> Add support for wildcard constants

- README.md
- lib/geoengineer/gps/gps.rb
- lib/geoengineer/utils/hash_utils.rb
- spec/gps/gps_spec.rb
This adds the ability to use `_default` as a special keyword for the environment
name so the block defined will be used as a template for all other known
environments, except if already defined.
This can be useful when a configuration has to be applied to all
environments. Rather than having to copy and paste an entry for each
environment, it can be defined once. YAML templating can be useful to minimize
how much is copied, but it becomes tedious as the list of environments grows.
Using _default allows the project to shift from being inclusionary to being
exclusionary. If the resources should exist in most environments, but not all,
and the list of ones to not is fairly static, you can exclude the configuration
from that environment just by defining an empty hash for that environment.
For …
> Adds ability to use _default as a special environment keyword

- README.md
- geoengineer.gemspec
- lib/geoengineer/resources/aws/vpc/aws_vpc_ipv4_cidr_block_association.rb
- lib/geoengineer/utils/has_validations.rb
Bumps `netaddr` to address CVE-2019-17383.
Required various changes to support moving from v1 to v2.
* Documented - happy to add more if helpful.
* Old function names no longer exist - hence the migration.
> [deps] bump netaddr version

- lib/geoengineer/backend.rb
- lib/geoengineer/cli/geo_cli.rb
- lib/geoengineer/cli/globals.rb
- lib/geoengineer/cli/terraform_commands.rb
- lib/geoengineer/environment.rb
Terraform supports storing and fetching state files from a remote location for the purposes of caching, security, and collaboration. GeoEngineer historically has not fetched a remotely shared state file, however in order to support better integration with Terraform, GeoEngineer will now support remote backends (https://www.terraform.io/docs/backends/index.html)
This PR adds the ability to configure a remote backend, which is bootstrapped when "terraform init" is called.
> Adding support for Terraform state file remote backends

- lib/geoengineer/resources/aws/kms/aws_kms_key.rb
Previously geoengineer only fetched the first 1000 keys – this ensures it fetches all keys in an account if it exceeds that number.
> Fetch all kms keys using pagination

- lib/geoengineer/gps/node.rb
Fix an error where GPS would break apart project names that have a `/` in them.
> [Fix] support deep project names

- lib/geoengineer/resources/aws/iam/aws_iam_role_policy_attachment.rb
- spec/resources/aws_iam_role_policy_attachment_spec.rb
This updates the `aws_iam_role_policy_attachment` handling to better support two
cases.
First, when to not error when the given policy ARN doesn't exist. This makes it
so Geoengineer won't error, but Terraform later will. The primary case is that
you might be creating the policy and the role attachment in the same run. Even
when adding the depends_on, Geoengineer would error out before it expects it to
already exist.
Second, it updates it to skip fetching when the policy ARN is formatted like a
Terraform reference. This also can happen in cases where creating the policy and
the attachment in the same run, or when populating the ARN with a reference
instead of hard setting the value.
This primarily benefits bootstrapping new things where common base resources are
created, like policies, …
> Update IAM role policy attach to handle ARN not existing and TF ref

- lib/geoengineer/cli/geo_cli.rb
If the remote state file backend is enabled, applies and plans run with a path to .rb or .gps.yml configuration files will cause terraform to propose resource deletions. This is because it believes configuration files have been deleted.
The code changes in this PR raise an exception if remote state files are supported in an environment and gps or rb files are provided in the geo cli command.
> Prevent running partial applies or plans when remote state enabled

- lib/geoengineer/resources/aws/s3/aws_s3_bucket_object.rb
A recent upgrade of the AWS provisioner seems to have resulted in unnecessary changes appearing for `aws_s3_bucket_object` resources.
Fix these by interpreting an empty string for force_destroy as 'false'.
This eliminates spurious plans like:
~ aws_s3_bucket_object.my_bucket_object
force_destroy:   "" => "false"
> Silence force_destroy updates for aws_s3_bucket_object

- lib/geoengineer/resources/aws/vpc/aws_vpc_endpoint.rb
This updates the `aws_vpc_endpoint` resource to enable tags and require it to
have a `Name` tag. Previously, it is likely it didn't support tags, but now it
does.
This is step 1 to including the Name tag in the geo_id so we can have multiple
endpoints per service type within a VPC. This is being done in 2 steps so we can
add Name tags to all existing resources before using it in the geo_id, as that
would want it to provision new endpoints for all existing uses.
> Updates aws_vpc_endpoint to allow tags and require a name tag
