lib/geoengineer/resources/aws_subnet.rb, spec/resources/aws_subnet_spec.rb
- New feature
Added the AWS Subnet resource to Geo.
Added some specs.
@mentions:
==========
@grahamjenson
=> New: Add AWS Subnet to Geo

lib/geoengineer/resources/aws_route_table.rb, lib/geoengineer/resources/aws_subnet.rb, lib/geoengineer/resources/aws_vpc.rb, spec/resources/aws_route_table_spec.rb
- New feature
Adding the ability to codify route tables to Geo.
Also simplify logic in a couple other resources by taking advantage of the fact that `find` returns `nil` if nothing is found.
Added a spec
@mentions:
==========
@grahamjenson
=> New: Add Aws Route Table to Geo

lib/geoengineer/resources/aws_internet_gateway.rb, spec/resources/aws_internet_gateway_spec.rb
- New feature
Add the ability to codify Aws Internet Gateway.
Pretty standard resource.
Added the usual specs.
=> New: Add Aws Internet Gateway

lib/geoengineer/resources/aws_route_table_association.rb, lib/geoengineer/resources/aws_vpc_endpoint.rb, spec/resources/aws_vpc_endpoint_spec.rb
- New feature
Added the ability to codify VPC Endpoints. Also fixed a bug in route
table associations.
Added the usual specs.
=> New: Add VPC Endpoint

lib/geoengineer/resources/aws_network_acl.rb, spec/resources/aws_network_acl_spec.rb
- New feature
Add Network ACL
The usual
=> New: Add AWS Network ACL

lib/geoengineer/resources/aws_vpn_connection.rb, lib/geoengineer/resources/aws_vpn_connection_route.rb, spec/resources/aws_network_acl_rule_spec.rb, spec/resources/aws_network_acl_spec.rb, spec/resources/aws_vpn_connection_route_spec.rb, spec/resources/aws_vpn_connection_spec.rb
- New feature
Added the ability to codify AWS VPN Connection and their associated
standalone routes.
Also fixed the test interaction between NACL & NACL Rule.
The usual specs
=> New: Add AWS VPN Connection And Route

lib/geoengineer/resources/aws_vpc_peering_connection.rb, spec/resources/aws_vpc_peering_connection_spec.rb
- New feature
Add the ability to codify VPC Peering Connections
The usual.
=> New: Add VPC Peering Connection

lib/geoengineer/resources/aws_lambda_alias.rb, lib/geoengineer/resources/aws_lambda_function.rb, lib/geoengineer/utils/aws_clients.rb, spec/resources/aws_lambda_alias_spec.rb, spec/resources/aws_lambda_function_spec.rb, spec/resources/aws_route53_record_spec.rb
- New feature
Add the ability to codify AWS lambda functions
The usual tests
@mentions:
==========
@lukedemi
=> New: Add AWS Lambda Function

lib/geoengineer/resources/aws_main_route_table_association.rb, spec/resources/aws_main_route_table_association_spec.rb
- New feature
Somehow this slipped my attention when going through the resources last
week. Discovered as I was trying to codify our networking layer.
So I added it.
Added the usual specs
@mentions:
==========
@grahamjenson
=> New: Add aws_main_route_table_association

lib/geoengineer/environment.rb, lib/geoengineer/project.rb, lib/geoengineer/template.rb, lib/geoengineer/utils/has_projects.rb, lib/geoengineer/utils/has_resources.rb, lib/geoengineer/utils/has_templates.rb, spec/environment_spec.rb, spec/project_spec.rb, spec/utils/has_resources_spec.rb
- Refactor
I thought it would be best to extend templating functionality to
environments as well as projects. This is my attempt at doing so in the
least painful, most extensible way. This means that we should aim to
avoid case x then... case y then... situations as much as possible.
The base API should be uniform to the point of minimality, and higher
level methods like `from_template` on `projects` and `environments`
should add additional functionality where necessary.
Todo
@mentions:
==========
@grahamjenson
=> Refactor: Templates

lib/geoengineer/resources/aws_elasticache_cluster.rb
- Refactor
Previously Elasticache was expecting a GeoEngineer Resource, which
doesn't play well if you have an ID, or if the Resource you codified is
in a different file...
@mentions:
==========
@rob
=> Refactor: Allow for ID Strings to be passed

lib/geoengineer/resources/aws_iam_role_policy.rb
=> name == policyName, which is what we want, not policy

lib/geoengineer/resources/aws_lambda_alias.rb
- Refactor
Needed to update the `tfstate` and the validations. The validations were inverted, so valid names were throwing `true` errors.
=> Refactor: Update the lambda alias

lib/geoengineer/resources/aws_iam_instance_profile.rb, spec/resources/aws_iam_instance_profile_spec.rb
This allows us to assign roles to instances.
=> geo should support instance profiles

Gemfile.lock, geoengineer.gemspec, grammar/terraform_plan.treetop, lib/geoengineer/cli/geo_cli.rb, lib/geoengineer/cli/terraform_commands.rb, lib/geoengineer/terraform_plan.rb, spec/spec_helper.rb, spec/support/normalize_indent.rb, spec/terraform_plan_spec.rb
We want to make diffs easier to read.
This improves output by detecting when attributes are JSON/multiline and formats them to be more legible. It also colorizes the diff of attribute changes to make them easier to read.
=> Improve plan output 

lib/geoengineer/cli/terraform_commands.rb
The original code assumed the buffer would be flushed on every newline,
which isn't necessarily the case. Modify the chunk inspection to
properly handle the case when the outputs markers (e.g. lines containing
`Path` and `Plan`) include additional newlines.
=> Fix Terraform plan chunk processing

lib/geoengineer/resources/aws_cloudfront_distribution.rb, lib/geoengineer/utils/aws_clients.rb, spec/resources/aws_cloudfront_distribution_spec.rb
This will allow us to codify CloudFront distributions!
=> Add aws_cloudfront_distribution resource

README.md, lib/geoengineer/cli/geo_cli.rb, lib/geoengineer/cli/terraform_commands.rb
Addresses the question raised in #127 .  I wasn't sure if any additional tests were needed since the added functionality is outside of Geoengineer.  Please let me know what you think!
=> Support destruction of resources with "geo destroy"

lib/geoengineer/resources/aws_customer_gateway.rb, lib/geoengineer/resources/aws_route53_record.rb, lib/geoengineer/resources/aws_vpn_connection.rb, lib/geoengineer/resources/aws_waf_ipset.rb, lib/geoengineer/resources/aws_waf_rule.rb, lib/geoengineer/resources/aws_waf_web_acl.rb, lib/geoengineer/utils/aws_clients.rb, spec/resources/aws_waf_ipset_spec.rb, spec/resources/aws_waf_rule_spec.rb, spec/resources/aws_waf_web_acl_spec.rb, spec/spec_helper.rb
I've been using these as part of an S3/Cloudfront website.
=> Adding WAF resources and fixing tests.

lib/geoengineer/resources/aws_route53_record.rb, lib/geoengineer/resources/aws_route53_zone.rb, lib/geoengineer/resources/aws_waf_ipset.rb, lib/geoengineer/utils/has_validations.rb
This fixes some tests and rubocop violations that have been on master.
@grahamjenson @jack-kearney
=> Fix tests and rubocop on master

lib/geoengineer/resource.rb, spec/resource_spec.rb
Sometimes, you want a resource that is _almost_ the same as an existing
resource, and you're too lazy to list out all those attributes twice, so
you're like "Hmm, I'll just duplicate this resource and change a few
things with my handy dandy #duplicate method".
Added some tests to ensure it behaves as expected.
=> [New] Resource Duplication

lib/geoengineer/resources/aws_rds_cluster.rb, lib/geoengineer/resources/aws_rds_cluster_instance.rb, lib/geoengineer/resources/aws_rds_cluster_parameter_group.rb, spec/resources/aws_rds_cluster_instance_spec.rb, spec/resources/aws_rds_cluster_parameter_group_spec.rb, spec/resources/aws_rds_cluster_spec.rb
Adds the aws_rds_cluster, aws_rds_cluster_instance, and aws_rds_cluster_parameter_group resources
=> Add aws_rds (aurora) resources

lib/geoengineer/resources/aws_kinesis_firehose_delivery_stream.rb
=> Terraform's aws provider doesnt set the kinesis source properly. 

lib/geoengineer/resources/aws_iam_saml_provider.rb, spec/resources/aws_iam_saml_provider_spec.rb
Add a geoengineer resource for aws_iam_saml_provider.
=> aws_iam_saml_provider

.rubocop.yml, lib/geoengineer/resource.rb, lib/geoengineer/resources/aws/codebuild/aws_codebuild_project.rb, lib/geoengineer/utils/aws_clients.rb, lib/geoengineer/utils/has_attributes.rb, spec/resources/aws_codebuild_project_spec.rb
also refactor of _json_file and assign attribute
=> [Feature] CodeBuild Project

.rubocop.yml, .rubocop_todo.yml, lib/geoengineer/cli/geo_cli.rb, lib/geoengineer/cli/terraform_commands.rb, lib/geoengineer/resources/aws/lb/aws_alb.rb, lib/geoengineer/resources/aws/lb/aws_lb.rb, spec/spec_helper.rb
This PR:
1. adds the `test` feature to geo to let a person build a terraform.json without hitting AWS
2. fixes the load_balancer default type issue
3. uniqs the returned errors for easier reading
4. fixes up some rspec issues
=> [Fix/Feature] adding test to CLI and fixing lb issue

lib/geoengineer/resources/aws/iam/aws_iam_user_policy_attachment.rb
This is superior to the aws_iam_policy_attachment.
=> [NEW] Add the IAM User Policy Attachment resource

lib/geoengineer/gps/gps.rb, spec/gps/gps_spec.rb
I had escaped the `-` too much. Fix that.
=> [FIX] \\- -> \-

README.md, lib/geoengineer/cli/geo_cli.rb, lib/geoengineer/cli/gps_commands.rb, lib/geoengineer/gps/node.rb
This command lets you interactively explore the GPS graph.
For example:
```
./geo query "*:*:*:postgres:*"
./geo query "infra/codeflow:*:*:service:*" --expanded
./geo query "*:production:*:s3:*" --attributes name
./geo query "*:*:*:*:*" --out graph.yml
```
Fun stuff
=> [NEW] Add ./geo query command

bin/geo, lib/geoengineer.rb, lib/geoengineer/cli/geo_cli.rb, lib/geoengineer/cli/globals.rb
=> [Refactor] include the GeoCLI class in the exports

lib/geoengineer/resources/aws/organizations/aws_organizations_account.rb
This updates it to retrieve all of the pages when dealing with more accounts.
=> Fix the `aws_organizations_account` resource to handle pagination

Gemfile, geoengineer.gemspec, lib/geoengineer/resources/aws/s3/aws_s3_bucket_policy.rb, lib/geoengineer/utils/aws_clients.rb, spec/resources/aws_s3_bucket_policy_spec.rb
This fixes the `./geo query` command by including the `tty-pager` gem.
It also adds the `aws_s3_bucket_policy` resource.
=> [FIX & NEW] Add S3 Bucket Policy, tty-pager gem

lib/geoengineer/gps/yaml_tag.rb, spec/gps/yaml_tag_spec.rb
Adds the ability for the `!sub` tag which replaces a strings values with references
=> [Feature] adds the sub tag

lib/geoengineer/resources/aws/db/aws_db_subnet_group.rb, spec/resources/aws_db_subnet_group_spec.rb
This will allow us to codify these resources.
=> [NEW] Add aws_db_subnet_group

lib/geoengineer/resources/aws/lb/aws_lb.rb, lib/geoengineer/resources/aws/vpc/aws_vpc_endpoint_service.rb, spec/resources/aws_vpc_endpoint_service_spec.rb
Modify aws_lb to support fetching the ARN to create a geo id for aws_vpc_endpoint_service resources.
=> Add the aws_vpc_endpoint_service resource

lib/geoengineer/cli/test_cmd_stubs.rb
AWS cannot auto generate some good stubs
=> [Fix] Some bad AWS stubs need fixing

lib/geoengineer/gps/gps.rb, lib/geoengineer/gps/node.rb
This just adds a few bits of error reporting
=> [Fix] Add some context to errors being reported

lib/geoengineer/gps/yaml_tag.rb
This will allow the subbing of lists using `!sub`
=> [Fix] allow lists in sub

README.md
* Improves the `README.md` making it a bit easier to get started.
I was stuck on not knowing I needed run `assume-role` prior to running `geo` given the error output received.  This clarifies that step.
=> [readme] improve getting started steps

lib/geoengineer/resources/aws/api_gateway/aws_api_gateway_domain_name.rb, lib/geoengineer/resources/aws/api_gateway/helpers.rb
=> [fix] add remote resource to aws_api_gateway_domain_name

.rubocop.yml, lib/geoengineer/resources/aws/api_gateway/aws_api_gateway_base_path_mapping.rb, lib/geoengineer/resources/aws/api_gateway/helpers.rb, lib/geoengineer/resources/aws/kinesis/aws_kinesis_firehose_delivery_stream.rb
Add aws_api_gateway_base_path_mapping resource type... because it wasn't there before.
=> add aws_api_gateway_base_path_mapping

lib/geoengineer/resources/aws/iam/aws_iam_policy.rb, lib/geoengineer/utils/has_validations.rb, spec/resources/aws_iam_policy_spec.rb
Require that either resource or notresource is set.
=> Add a validation on statements within a policy.

README.md
=> Add additional documentation on adding providers/resources

lib/geoengineer/gps/gps.rb
Remove the PWD from the directory check.
=> [Fix] path error

lib/geoengineer/resources/aws/msk/aws_msk_cluster.rb, lib/geoengineer/resources/aws/msk/aws_msk_configuration.rb, lib/geoengineer/utils/aws_clients.rb, spec/resources/aws_msk_cluster_spec.rb, spec/resources/aws_msk_configuration_spec.rb
Borrowed implementations mainly from `aws_dynamodb_table.rb`.
=> Add aws_msk_cluster and aws_msk_configuration terrform resources

lib/geoengineer/gps/gps.rb
This will prevent any sort of ERB rendering of GPS files.
=> Remove the ERB rendering for GPS files.

lib/geoengineer/gps/gps.rb, lib/geoengineer/gps/node.rb
This fixes a small depends on issue
=> [Fix] metadata nodes pass along dependencies to built nodes

geoengineer.gemspec, lib/geoengineer/resources/aws/kms/aws_kms_key.rb
This is a bandaid to allow you to fetch more KMS keys if you have more than 100.
=> Fetch more KMS keys because this doesnt paginate.

lib/geoengineer/resources/aws/s3/aws_s3_bucket_object.rb
Previously the s3 bucket object did not fetch remote resources – this adds individual fetching for each defined resource
=> Add remote fetching of s3 bucket objects

lib/geoengineer/gps/gps.rb
Right now we are swallowing part of our stacktrace. Improve our error handling to make sure we show the true stacktrace while annotating the error with useful information.
=> Better error handling

lib/geoengineer/resources/aws/cloudwatch/aws_cloudwatch_event_target.rb, lib/geoengineer/resources/aws/ec2/aws_instance.rb, lib/geoengineer/resources/aws/efs/aws_efs_file_system.rb, lib/geoengineer/resources/aws/efs/aws_efs_mount_target.rb, lib/geoengineer/resources/aws/kinesis/aws_kinesis_stream.rb
Not passing in a provider does not preserve region preferences.
=> Fix multi region code.

lib/geoengineer/cli/geo_cli.rb
**What changed? Why?**
Output by GeoEngineer is extremely verbose.
By default this filters out `Refreshing state...` on `apply`.
This output can be shown by adding `--show-refresh-state`.
**How has it been tested?**
Local runs so far have been as expected.
Will await reviews.
**Change management**
type=routine
risk=low
impact=sev5
=> [apply] filter refreshing state by default

lib/geoengineer/resources/aws/lb/aws_lb_target_group.rb
Make sure they show up in the remote state. This allows users to set values such as proxy_protocol_v2.
=> Start fetching attributes for lb targets. 
